create table authority (id varchar(36) not null, authority varchar(255), primary key (id)) engine=InnoDB;
create table league (game tinyint, is_open bit not null, max_number_of_teams integer not null, id bigint not null auto_increment, owner_id bigint, starts datetime(6), description varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table league_matches (league_id bigint not null, matches_id bigint not null) engine=InnoDB;
create table maches (scorea integer, scoreb integer, id bigint not null auto_increment, league_id bigint, starts datetime(6), teama_id bigint, teamb_id bigint, primary key (id)) engine=InnoDB;
create table score (id bigint not null auto_increment, primary key (id)) engine=InnoDB;
create table team (id bigint not null auto_increment, owner_id bigint, name varchar(255), primary key (id)) engine=InnoDB;
create table team_matches (matches_id bigint not null, team_id bigint not null) engine=InnoDB;
create table team_players (players_id bigint not null, team_id bigint not null) engine=InnoDB;
create table users (account_non_expired bit not null, account_non_locked bit not null, credentials_non_expired bit not null, enabled bit not null, id bigint not null auto_increment, team_id bigint, name varchar(255), password varchar(255), picture varchar(255), provider varchar(255), provider_id varchar(255), username varchar(255), primary key (id)) engine=InnoDB;
create table users_authorities (user_id bigint not null, authorities_id varchar(36) not null, primary key (user_id, authorities_id)) engine=InnoDB;
create table users_owned_leagues (owned_leagues_id bigint not null, user_id bigint not null) engine=InnoDB;
alter table league_matches add constraint UK_bw2qjvedqigcjdxmu2hq9e8sa unique (matches_id);
alter table team add constraint UK_frjxgaag9ypwhjyf7y3p5o3of unique (owner_id);
alter table team_matches add constraint UK_ca2prqkp1fs3h2l49re9ytvgt unique (matches_id);
alter table team_players add constraint UK_j7gm7vpm2kn3c07shxqlvt4al unique (players_id);
alter table users add constraint UK_r43af9ap4edm43mmtq01oddj6 unique (username);
alter table users_authorities add constraint UK_4k9modmi5xv8km1qoyfyrjhjt unique (authorities_id);
alter table users_owned_leagues add constraint UK_2mt6wo1ic3c2bd74p8284b214 unique (owned_leagues_id);
alter table league add constraint FKrfq864akaefqxwn5rqxjjn1rr foreign key (owner_id) references users (id);
alter table league_matches add constraint FKn1owt3t73jnntth2ulu0aed89 foreign key (matches_id) references maches (id);
alter table league_matches add constraint FKbli33wr6ag0k72abj073tgqwf foreign key (league_id) references league (id);
alter table maches add constraint FK1lphyja8bqa7uk3b3heekb49 foreign key (league_id) references league (id);
alter table maches add constraint FK9r3xk5qicydlyvbdkogein41d foreign key (teama_id) references team (id);
alter table maches add constraint FKrf9wbgjddk2fdothh3d9239ap foreign key (teamb_id) references team (id);
alter table team add constraint FKgdpoe95qkeodr9j476t8emoxl foreign key (owner_id) references users (id);
alter table team_matches add constraint FKj6u5g3xi2adybuhltev60lapn foreign key (matches_id) references maches (id);
alter table team_matches add constraint FKd9dx2hnof5j3nkoh6qvo78ok8 foreign key (team_id) references team (id);
alter table team_players add constraint FKfdnnvq9o1f5451wl15foasmb1 foreign key (players_id) references users (id);
alter table team_players add constraint FKc9igy2kys82rwa80px3q0usqa foreign key (team_id) references team (id);
alter table users add constraint FKhn2tnbh9fqjqeuv8ehw5ple7a foreign key (team_id) references team (id);
alter table users_authorities add constraint FKt25vmk46t0o0x01yo0wyx7wmf foreign key (authorities_id) references authority (id);
alter table users_authorities add constraint FKq3lq694rr66e6kpo2h84ad92q foreign key (user_id) references users (id);
alter table users_owned_leagues add constraint FKcxq3smveb29oid2laacxqjx5h foreign key (owned_leagues_id) references league (id);
alter table users_owned_leagues add constraint FKjhh11aaqdfnq1iqukhxupkn9w foreign key (user_id) references users (id);
