spring:
  datasource:
    url: jdbc:mysql://localhost:3306/CyberLeagues
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${client.id}
            client-secret: ${client.secret}